server:
  port: 8080
spring:
  flyway:
    enabled: true
    schemas: customer
    url: ${spring.datasource.host}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    url: ${spring.datasource.host}/customer?nullCatalogMeansCurrent=true
    host: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: qnbeyond2022
  expirationMs: 86400000
